lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    token_extractors:
        authorization_header:
            enabled: true

        cookie:
            enabled: true

    set_cookies:
        BEARER:
            lifetime: 259200 # set same as refresh to get good error message
            domain: '%env(COOKIE_DOMAIN)%'
